version: '3.8'
services:
  client:
    container_name: react-app
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: on-failure
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./client:/app
      - /app/node_modules

  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: setlist_app
      PGPORT: 5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  server:
    container_name: express-api
    depends_on:
      - db
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: on-failure
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/setlist_app
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
      - /app/node_modules
    # command: npm run migrate

  migration:
    container_name: postgrator
    depends_on:
      - server
    build:
      context: ./server
      dockerfile: Dockerfile.migrate
    restart: on-failure
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/setlist_app
    command: npm run migrate

volumes:
  pg_data:
